name: Build icons

on:
  # Triggers the workflow on pull request events but only for the "main" branch
  pull_request:
    branches: ["main"]

env:
  FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
  FIGMA_FILE_ID: ${{ secrets.FIGMA_FILE_ID }}
  FIGMA_PAGE_NAME: icons

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version-file: ".nvmrc"
      - run: |
          npm ci
          npm run build
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Export icons."
          git push
